import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const MARKER = "<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->";
export const OWNER_REPO = "ryanportfolio/HarnessFirmware.com";
export const PRODUCT_REPO = "https://github.com/ryanportfolio/Harness-Firmware";

export function absolute(relativePath) {
  return path.join(ROOT, relativePath);
}

export function read(relativePath) {
  return fs.readFileSync(absolute(relativePath), "utf8");
}

export function readJson(relativePath) {
  return JSON.parse(read(relativePath));
}

export function writeText(relativePath, value) {
  const target = absolute(relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, value.replaceAll("\r\n", "\n"), "utf8");
}

export function esc(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export function fail(message) {
  process.stderr.write(`FAIL ${message}\n`);
  process.exitCode = 1;
}
