// Unit tests for the template drift check. Fixture data only; nothing here touches the network.
import assert from 'node:assert/strict';
import { test } from 'node:test';
import {
  TEMPLATE_REPOSITORY,
  catalogDifferences,
  fetchUpstreamRecord,
  recordDifferences,
  skillNames,
  skillRulesText,
  upstreamRecord,
} from './refresh-upstream-skills.mjs';

const blob = (path) => ({ path, mode: '100644', type: 'blob', sha: 'a' });

// A small template: alpha in both runtimes, beta Claude only, gamma Codex only, plus a Codex folder
// with no SKILL.md (not a skill) and a nested SKILL.md (not a skill folder of its own).
function fixtureTree() {
  return [
    blob('.claude/skills/alpha/SKILL.md'),
    blob('.claude/skills/alpha/references/notes.md'),
    blob('.claude/skills/beta/SKILL.md'),
    blob('.agents/skills/alpha/SKILL.md'),
    blob('.agents/skills/gamma/SKILL.md'),
    blob('.agents/skills/retired-resources/LICENSE.txt'),
    blob('.agents/skills/gamma/examples/inner/SKILL.md'),
    { path: '.claude/skills/alpha', mode: '040000', type: 'tree', sha: 't' },
  ];
}

function fixtureManifest() {
  return {
    version: 1,
    requiredFiles: ['AGENTS.md'],
    templateOnly: ['README.md'],
    readmeStub: '# {name}\n',
    skills: {
      groups: [
        { id: 'core', label: 'Core', description: 'Core skills', skills: ['beta', 'alpha'] },
        { id: 'extra', label: 'Extra', description: 'Extra skills', skills: ['gamma'] },
      ],
      required: ['alpha'],
      dependencies: { gamma: ['beta', 'alpha'] },
    },
  };
}

const record = () => upstreamRecord({ commit: 'c'.repeat(40), treeEntries: fixtureTree(), manifest: fixtureManifest() });

// The site side that matches the fixture template exactly.
function matchingSite() {
  return {
    catalog: [
      { name: 'alpha', group: 'core' },
      { name: 'beta', group: 'core', runtime: 'claude' },
      { name: 'gamma', group: 'extra', runtime: 'codex' },
    ],
    groups: [
      { id: 'core', label: 'Core', description: 'Core skills' },
      { id: 'extra', label: 'Extra', description: 'Extra skills' },
    ],
    required: ['alpha'],
    dependencies: { gamma: ['alpha', 'beta'] },
  };
}

test('skill folders are the folders that directly hold a SKILL.md', () => {
  assert.deepEqual(skillNames(fixtureTree(), '.claude/skills'), ['alpha', 'beta']);
  assert.deepEqual(skillNames(fixtureTree(), '.agents/skills'), ['alpha', 'gamma']);
});

test('the record carries runtimes, sorted groups, and sorted rules from the manifest', () => {
  assert.deepEqual(record(), {
    repository: TEMPLATE_REPOSITORY,
    commit: 'c'.repeat(40),
    claude: ['alpha', 'beta'],
    codex: ['alpha', 'gamma'],
    groups: [
      { id: 'core', label: 'Core', description: 'Core skills', skills: ['alpha', 'beta'] },
      { id: 'extra', label: 'Extra', description: 'Extra skills', skills: ['gamma'] },
    ],
    removal: { required: ['alpha'], dependencies: { gamma: ['alpha', 'beta'] } },
  });
  assert.throws(() => upstreamRecord({ commit: 'c', treeEntries: [], manifest: { ...fixtureManifest(), version: 2 } }), /version 2/);
});

test('generated rules evaluate to the record rules', async () => {
  const text = skillRulesText(record());
  assert.match(text, /^\/\/ Generated by scripts\/refresh-upstream-skills\.mjs from skills\.required and skills\.dependencies/);
  assert.doesNotMatch(text, /c{40}/, 'the rules carry no commit');
  const rules = await import(`data:text/javascript,${encodeURIComponent(text)}`);
  assert.deepEqual(rules.HARNESS_REQUIRED_SKILLS, ['alpha']);
  assert.deepEqual(rules.HARNESS_SKILL_DEPENDENCIES, { gamma: ['alpha', 'beta'] });
});

test('a site that matches the template reports nothing', () => {
  assert.deepEqual(catalogDifferences(record(), matchingSite()), []);
});

test('a skill the template has and the catalog lacks is reported', () => {
  const site = matchingSite();
  site.catalog = site.catalog.filter((skill) => skill.name !== 'gamma');
  assert.deepEqual(catalogDifferences(record(), site), ['catalog is missing gamma (codex only in the template)']);
});

test('a catalog skill the template does not have is reported', () => {
  const site = matchingSite();
  site.catalog.push({ name: 'delta', group: 'core' });
  assert.deepEqual(catalogDifferences(record(), site), ['catalog lists delta, which the template does not have']);
});

test('a runtime mismatch is reported', () => {
  const site = matchingSite();
  delete site.catalog[1].runtime;
  site.catalog[2].runtime = 'claude';
  assert.deepEqual(catalogDifferences(record(), site), [
    'beta runtime: catalog says both runtimes, template has claude only',
    'gamma runtime: catalog says claude only, template has codex only',
  ]);
});

test('a group mismatch is reported, for skills and for group copy', () => {
  const site = matchingSite();
  site.catalog[0].group = 'extra';
  site.groups[1] = { ...site.groups[1], label: 'Others' };
  assert.deepEqual(catalogDifferences(record(), site), [
    'alpha group: catalog says extra, manifest says core',
    'catalog groups are core (Core: Core skills); extra (Others: Extra skills); manifest groups are core (Core: Core skills); extra (Extra: Extra skills)',
  ]);
});

test('a dependency mismatch is reported', () => {
  const site = matchingSite();
  site.dependencies = { gamma: ['alpha'], beta: ['alpha'] };
  assert.deepEqual(catalogDifferences(record(), site), [
    'beta needs: rules say alpha, manifest says nothing',
    'gamma needs: rules say alpha, manifest says alpha, beta',
  ]);
});

test('a required mismatch is reported', () => {
  const site = matchingSite();
  site.required = ['alpha', 'beta'];
  assert.deepEqual(catalogDifferences(record(), site), ['required skills: rules say alpha, beta, manifest says alpha']);
});

test('manifest groups that miss or repeat a skill are reported', () => {
  const manifest = fixtureManifest();
  manifest.skills.groups[0].skills = ['alpha', 'ghost'];
  manifest.skills.groups[1].skills = ['gamma', 'alpha'];
  const live = upstreamRecord({ commit: 'c', treeEntries: fixtureTree(), manifest });
  assert.deepEqual(catalogDifferences(live, matchingSite()), [
    'manifest group core lists ghost, which has no skill folder',
    'manifest puts alpha in both core and extra',
    'beta has no group in the manifest',
  ]);
});

test('the committed record drifts on skills, groups, rules, and stale keys, never on the commit alone', () => {
  const live = record();
  assert.deepEqual(recordDifferences({ ...live, commit: 'd'.repeat(40) }, live), []);
  const committed = {
    ...structuredClone(live),
    claude: ['alpha', 'old'],
    retired: ['old'],
  };
  committed.groups[0].skills = ['alpha'];
  committed.removal.dependencies = {};
  assert.deepEqual(recordDifferences(committed, live), [
    'upstream-skills.json: has "retired", which the refresh no longer writes',
    'upstream-skills.json claude skills: missing beta',
    'upstream-skills.json claude skills: has old, which the template does not',
    'upstream-skills.json: skill groups differ from the manifest',
    'upstream-skills.json: removal rules differ from the manifest',
  ]);
});

test('the fetch reads the tree and manifest at the commit the ref resolves to', async () => {
  const commit = 'e'.repeat(40);
  const requests = [];
  const fetchImpl = async (url, init) => {
    requests.push({ url, headers: init.headers });
    const body = url.endsWith('/commits/main') ? { sha: commit }
      : url.includes('/git/trees/') ? { tree: fixtureTree(), truncated: false }
        : url.includes('/contents/') ? fixtureManifest()
          : null;
    return { ok: body !== null, status: body ? 200 : 404, json: async () => body };
  };
  const live = await fetchUpstreamRecord('main', { fetchImpl, token: 'secret' });
  assert.deepEqual(live, { ...record(), commit });
  const api = `https://api.github.com/repos/${TEMPLATE_REPOSITORY}`;
  assert.deepEqual(requests.map((request) => request.url), [
    `${api}/commits/main`,
    `${api}/git/trees/${commit}?recursive=1`,
    `${api}/contents/.agents/template-manifest.json?ref=${commit}`,
  ]);
  assert.ok(requests.every((request) => request.headers.Authorization === 'Bearer secret'));
  assert.equal(requests[2].headers.Accept, 'application/vnd.github.raw+json');

  const truncated = async (url) => ({ ok: true, json: async () => (url.includes('/git/trees/') ? { tree: [], truncated: true } : { sha: commit }) });
  await assert.rejects(fetchUpstreamRecord('main', { fetchImpl: truncated, token: '' }), /truncated/);
});
